upgrade to marqo 2.10
marqo-ai/marqo-on-kubernetes pull request #8
Opened 2024-07-24 01:00 UTC by ali60

2024-07-25 22:54 UTC, wanliAlex requested changes

2024-07-25 22:54 UTC, wanliAlex commented on chart/marqo-kubernetes/values.yaml
> +    tag: 2.10.0
The latest Marqo version is 2.10.1

2024-07-26 00:05 UTC, Mehul-Porwal approved these changes

2024-07-26 00:08 UTC, Mehul-Porwal requested changes
Vespa update will fails as we are jumping too many versions.

2024-07-26 00:15 UTC, Mehul-Porwal commented
We should either set `VESPA_SKIP_UPGRADE_CHECK=TRUE` in the vespa configmap or document that for user's in the readme.

2024-07-26 00:23 UTC, wanliAlex approved these changes

2024-07-26 04:56 UTC, Mehul-Porwal approved these changes

2024-07-26 05:19 UTC, merged